package exception;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class ExceptionTest2_t {
	private int dan;
	public void input() throws IOException {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		System.out.print("원하는 입력: ");
		dan = Integer.parseInt(br.readLine());
		if(dan>10 || dan<2) {
			System.out.println("범위를 벗어났습니다.");
			return;
		}
		
	}
	public void output() {
		for(int i=1;i<=9;i++) {
			System.out.println(dan+"*"+i+"="+dan*i);
		}
	}
	public static void main(String[] args) throws IOException {
		ExceptionTest2_t e2 = new ExceptionTest2_t();
		e2.input(); //Exception걸어놓은 메소드 부르면 호출부에서도 Exception처리해줘야함.
		e2.output();
	}
}
